Model ::= Entity+
Entity ::= "entity" Identifier ("(" Alias ")")? "{" Attribute+ "}"
Identifier ::= Letter | "_" | "$" (Letter | "_" | "$" | Digit)*
Alias ::= Identifier
Attribute ::= "*"? Identifier ("(" Alias ")")? ":" Type "!"? | Identifier "=" JSON
Type ::= DataType
     | EntityName
     | "[" EntityName "]" ("." AttributeName)?
     | "<" EntityName ">" ("." AttributeName)?
     | "[" EntityName "]" ("." AttributeName)? "(" EntityName ")"
DataType ::= "text"
              | "integer" | "int" | "int4"
              | "bool" | "boolean"
              | "bigint"
              | "decimal"
              | "date"
              | "float" | "float8"
              | "uuid"
              | "timestamp"
EntityName ::= Identifier
AttributeName ::= Identifier

/* https://www.w3.org/TR/2010/REC-xquery-20101214/#EBNFNotation */

/* color: #009688 (teal) */